
export const XNARates1 = [
    {
      key: 1,
      countryAbbre: "AUD",
      countryName: " Australian Dollar",
      XNA: "1 XNA",
      currency: "AUD",
    },
    {
      key: 2,
      countryAbbre: "CAD",
      countryName: " Canadian Dollar",
      XNA: "1 XNA",
      currency: "CAD",
    },
    {
      key: 3,
      countryAbbre: "CHF",
      countryName: " Swiss Franc",
      XNA: "1 XNA",
      currency: "CHF",
    },
    {
      key: 4,
      countryAbbre: "CNY",
      countryName: " Chinese Yuan Renminbi",
      XNA: "1 XNA",
      currency: "CNY",
    },
    {
      key: 5,
      countryAbbre: "DKK",
      countryName: " Danish Krone",
      XNA: "1 XNA",
      currency: "DKK",
    },
    {
      key: 6,
      countryAbbre: "EUR",
      countryName: "Euro",
      XNA: "1 XNA",
      currency: "EUR",
    },
    {
      key: 7,
      countryAbbre: "GBP",
      countryName: " British Pound",
      XNA: "1 XNA",
      currency: "GBP",
    },
    {
      key: 8,
      countryAbbre: "INR",
      countryName: " Indian Rupee",
      XNA: "1 XNA",
      currency: "INR",
    },
    {
      key: 9,
      countryAbbre: "JPY",
      countryName: "Japanese Yen",
      XNA: "1 XNA",
      currency: "JPY",
    },
    {
      key: 10,
      countryAbbre: "KWD",
      countryName: " Kuwaiti Dinar",
      XNA: "1 XNA",
      currency: "KWD",
    },
    {
      key: 11,
      countryAbbre: "MYR",
      countryName: "Malaysian Ringgit",
      XNA: "1 XNA",
      currency: "MYR",
    },
    {
      key: 12,
      countryAbbre: "NOK",
      countryName: " Norwegian Krone",
      XNA: "1 XNA",
      currency: "NOK",
    },
    {
      key: 13,
      countryAbbre: "PKR",
      countryName: "Pakistani Rupee",
      XNA: "1 XNA",
      currency: "PKR",
    },
    {
      key: 14,
      countryAbbre: "QAR",
      countryName: " Qatari Riyal",
      XNA: "1 XNA",
      currency: "QAR",
    },
    {
      key: 15,
      countryAbbre: "RUB",
      countryName: "Russian Ruble",
      XNA: "1 XNA",
      currency: "RUB",
    },
    {
      key: 16,
      countryAbbre: "SEK",
      countryName: "Swedish Krona",
      XNA: "1 XNA",
      currency: "SEK",
    },
    {
      key: 17,
      countryAbbre: "SGD",
      countryName: " Singapore Dollar",
      XNA: "1 XNA",
      currency: "SGD",
    },
    {
      key: 18,
      countryAbbre: "TRY",
      countryName: " Turkish Lira",
      XNA: "1 XNA",
      currency: "TRY",
    },
    {
      key: 19,
      countryAbbre: "USD",
      countryName: " US Dollar",
      XNA: "1 XNA",
      currency: "USD",
    },
  ];